---
# Ultra-minimal SDL for testing provider bids
# Public nginx image, no custom domain

version: "2.0"

services:
  web:
    image: nginx:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          - size: 512Mi

  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 500

deployment:
  web:
    dcloud:
      profile: web
      count: 1
