---
# Akash SDL (Stack Definition Language) for Alternate Futures Backend
# This deploys the GraphQL API + PostgreSQL + Self-Hosted IPFS to Akash Network

version: "2.0"

services:
  postgres:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=alternatefutures
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here_change_this
    expose:
      - port: 5432
        as: 5432
        to:
          - service: api
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data
          readOnly: false

  # IPFS Node (Kubo) - Self-hosted decentralized storage
  ipfs:
    image: ipfs/kubo:latest
    env:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    expose:
      # API port (for API service to connect)
      - port: 5001
        as: 5001
        to:
          - service: api
      # Gateway port (public access to IPFS content)
      - port: 8080
        as: 8080
        to:
          - global: true
        accept:
          - ipfs.alternatefutures.ai
      # Swarm port (P2P connections to IPFS network)
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true
    params:
      storage:
        data:
          mount: /data/ipfs
          readOnly: false

  api:
    image: alternatefutures/backend:latest
    env:
      # Database
      - DATABASE_URL=postgresql://postgres:your_secure_password_here_change_this@postgres:5432/alternatefutures

      # App Config
      - NODE_ENV=production
      - PORT=4000

      # JWT Secret (CHANGE THIS!)
      - JWT_SECRET=your_jwt_secret_min_32_chars_please_change_this_in_production

      # Email (Resend)
      - RESEND_API_KEY=your_resend_api_key

      # Storage - Self-Hosted IPFS (Primary)
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_GATEWAY_URL=https://ipfs.alternatefutures.ai

      # Storage - Pinata IPFS (Fallback - optional, only used if IPFS_API_URL not set)
      - PINATA_API_KEY=your_pinata_api_key_optional
      - PINATA_API_SECRET=your_pinata_api_secret_optional

      # Storage - Arweave
      - TURBO_WALLET_KEY=your_turbo_wallet_key

      # Storage - Filecoin
      - LIGHTHOUSE_API_KEY=your_lighthouse_api_key

      # Optional: Analytics
      - SENTRY_DSN=your_sentry_dsn

    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api.alternatefutures.ai
    depends_on:
      - postgres
      - ipfs

profiles:
  compute:
    api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 512Mi

    postgres:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          size: 10Gi

    ipfs:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          # Large storage for IPFS blocks and pinned content
          size: 100Gi

  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000
        postgres:
          denom: uakt
          amount: 1000
        ipfs:
          denom: uakt
          amount: 2000

deployment:
  api:
    dcloud:
      profile: api
      count: 1

  postgres:
    dcloud:
      profile: postgres
      count: 1

  ipfs:
    dcloud:
      profile: ipfs
      count: 1
