---
# OpenRegistry + Self-Hosted IPFS Deployment on Akash Network
# Fully Decentralized Container Registry with own IPFS node
version: "2.0"

services:
  # PostgreSQL - Metadata storage
  postgres:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=open_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHANGE_THIS_PASSWORD_IN_PRODUCTION
    expose:
      - port: 5432
        to:
          - service: registry

  # IPFS Node (Kubo) - Decentralized storage
  ipfs:
    image: ipfs/kubo:latest
    env:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    expose:
      # API port (for registry to connect)
      - port: 5001
        to:
          - service: registry
      # Gateway port (public access to content)
      - port: 8080
        as: 8080
        to:
          - global: true
        accept:
          - ipfs.alternatefutures.ai
      # Swarm port (P2P connections)
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true

  # OpenRegistry - OCI-compliant container registry
  registry:
    image: jasdeepsingh/open-registry:beta
    env:
      # Core Configuration
      - OPEN_REGISTRY_DEBUG=false
      - OPEN_REGISTRY_DOMAIN=registry.alternatefutures.ai
      - OPEN_REGISTRY_VERSION=beta
      - OPEN_REGISTRY_HOST=0.0.0.0
      - OPEN_REGISTRY_PORT=5000
      - OPEN_REGISTRY_SIGNING_SECRET=CHANGE_THIS_JWT_SECRET_MIN_32_CHARS
      - OPEN_REGISTRY_ENVIRONMENT=production

      # Database Configuration
      - OPEN_REGISTRY_DB_HOST=postgres
      - OPEN_REGISTRY_DB_PORT=5432
      - OPEN_REGISTRY_DB_USER=postgres
      - OPEN_REGISTRY_DB_PASSWORD=CHANGE_THIS_PASSWORD_IN_PRODUCTION
      - OPEN_REGISTRY_DB_NAME=open_registry

      # Storage Backend - Self-Hosted IPFS
      - OPEN_REGISTRY_DFS_IPFS_ENABLED=true
      - OPEN_REGISTRY_DFS_IPFS_API_URL=http://ipfs:5001
      - OPEN_REGISTRY_DFS_IPFS_GATEWAY_URL=http://ipfs:8080

      # Supported Auth Services
      - OPEN_REGISTRY_SUPPORTED_SERVICES=token

    expose:
      - port: 5000
        as: 80
        to:
          - global: true
        accept:
          - registry.alternatefutures.ai

profiles:
  compute:
    postgres:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 20Gi

    ipfs:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          # Large storage for IPFS blocks
          size: 100Gi

    registry:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 10Gi

  placement:
    akash:
      pricing:
        postgres:
          denom: uakt
          amount: 1000
        ipfs:
          denom: uakt
          amount: 2000
        registry:
          denom: uakt
          amount: 1000

deployment:
  postgres:
    akash:
      profile: postgres
      count: 1

  ipfs:
    akash:
      profile: ipfs
      count: 1

  registry:
    akash:
      profile: registry
      count: 1
