---
# Production Deployment with Infisical for Secrets
# Prerequisites:
# 1. Deploy Infisical first (deploy-infisical.yaml)
# 2. Build and publish Docker images to GHCR
# 3. Add secrets to Infisical via UI or CLI
# 4. Generate service token from Infisical

version: "2.0"

services:
  # IPFS Node
  ipfs:
    image: ipfs/kubo:latest
    env:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
        accept:
          - ipfs.alternatefutures.ai
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true
    params:
      storage:
        data:
          mount: /data/ipfs
          readOnly: false

  # YugabyteDB Node 1
  yb-node-1:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      # Infisical connection
      - INFISICAL_TOKEN=PLACEHOLDER_INFISICAL_SERVICE_TOKEN
      - INFISICAL_SITE_URL=https://secrets.alternatefutures.ai
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-2
          - service: yb-node-3
      - port: 9100
        as: 9100
        to:
          - service: yb-node-2
          - service: yb-node-3
      - port: 15000
        as: 15000
        to:
          - global: true
        accept:
          - yb.alternatefutures.ai
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # YugabyteDB Node 2
  yb-node-2:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-2"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - INFISICAL_TOKEN=PLACEHOLDER_INFISICAL_SERVICE_TOKEN
      - INFISICAL_SITE_URL=https://secrets.alternatefutures.ai
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-3
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-3
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # YugabyteDB Node 3
  yb-node-3:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-3"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - INFISICAL_TOKEN=PLACEHOLDER_INFISICAL_SERVICE_TOKEN
      - INFISICAL_SITE_URL=https://secrets.alternatefutures.ai
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-2
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-2
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # API Service (fetches all secrets from Infisical)
  # NOTE: Requires ghcr.io/alternatefutures/service-cloud-api:latest to be built and published
  api:
    image: ghcr.io/alternatefutures/service-cloud-api:latest
    env:
      # Non-sensitive config
      - NODE_ENV=production
      - PORT=4000

      # Infisical connection (service token is rotatable)
      - INFISICAL_TOKEN=PLACEHOLDER_INFISICAL_SERVICE_TOKEN
      - INFISICAL_SITE_URL=https://secrets.alternatefutures.ai
      - INFISICAL_PROJECT_ID=PLACEHOLDER_PROJECT_ID
      - INFISICAL_ENVIRONMENT=production

      # All other secrets fetched from Infisical at runtime:
      # - DATABASE_URL
      # - JWT_SECRET
      # - RESEND_API_KEY
      # - ARWEAVE_WALLET
      # etc.
    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api.alternatefutures.ai
    depends_on:
      - yb-node-1
      - yb-node-2
      - yb-node-3
      - ipfs

profiles:
  compute:
    yb-node-1:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - name: data
            size: 50Gi

    yb-node-2:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - name: data
            size: 50Gi

    yb-node-3:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - name: data
            size: 50Gi

    api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 512Mi

    ipfs:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - name: data
            size: 100Gi

  placement:
    dcloud:
      # REQUIRE AUDITED PROVIDERS
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      attributes:
        host: akash
      pricing:
        yb-node-1:
          denom: uakt
          amount: 50
        yb-node-2:
          denom: uakt
          amount: 50
        yb-node-3:
          denom: uakt
          amount: 50
        api:
          denom: uakt
          amount: 30
        ipfs:
          denom: uakt
          amount: 70

deployment:
  yb-node-1:
    dcloud:
      profile: yb-node-1
      count: 1

  yb-node-2:
    dcloud:
      profile: yb-node-2
      count: 1

  yb-node-3:
    dcloud:
      profile: yb-node-3
      count: 1

  api:
    dcloud:
      profile: api
      count: 1

  ipfs:
    dcloud:
      profile: ipfs
      count: 1
