---
# Akash SDL for TESTNET/SANDBOX Testing
# This is identical to deploy.yaml but for testing before mainnet deployment

version: "2.0"

services:
  # YugabyteDB Node 1 - Master + TServer
  yb-node-1:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=BbNB9snW285W7zIS7qX0+5ZbCWAzk1tdowzKv9dEpSU=
      - YSQL_DB=alternatefutures
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-2
          - service: yb-node-3
      - port: 9100
        as: 9100
        to:
          - service: yb-node-2
          - service: yb-node-3
      - port: 15000
        as: 15000
        to:
          - global: true
        accept:
          - yb-test.alternatefutures.ai
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  yb-node-2:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-2"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=BbNB9snW285W7zIS7qX0+5ZbCWAzk1tdowzKv9dEpSU=
      - YSQL_DB=alternatefutures
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-3
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-3
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  yb-node-3:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-3"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=BbNB9snW285W7zIS7qX0+5ZbCWAzk1tdowzKv9dEpSU=
      - YSQL_DB=alternatefutures
    expose:
      - port: 5433
        as: 5433
        to:
          - service: api
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-2
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-2
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # IPFS Node (Kubo) - Self-hosted decentralized storage
  ipfs:
    image: ipfs/kubo:latest
    env:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    expose:
      - port: 5001
        as: 5001
        to:
          - service: api
      - port: 8080
        as: 8080
        to:
          - global: true
        accept:
          - ipfs-test.alternatefutures.ai
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true
    params:
      storage:
        data:
          mount: /data/ipfs
          readOnly: false

  # GraphQL API Service
  api:
    image: ghcr.io/alternatefutures/service-cloud-api:latest
    env:
      - DATABASE_URL=postgresql://yugabyte:BbNB9snW285W7zIS7qX0+5ZbCWAzk1tdowzKv9dEpSU=@yb-node-1:5433/alternatefutures
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=78LyP5bLyk94mGVid3P2RKucRE8vJRQAe6Tyjqqsba/H+zHKpE4IAulU+PodgDAOLCHqLsSfSUnlShtq4yu/aQ==
      - RESEND_API_KEY=your_resend_api_key
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_GATEWAY_URL=https://ipfs-test.alternatefutures.ai
      - TURBO_WALLET_KEY=your_turbo_wallet_key
      - LIGHTHOUSE_API_KEY=your_lighthouse_api_key
      - SENTRY_DSN=your_sentry_dsn
    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api-test.alternatefutures.ai
    depends_on:
      - yb-node-1
      - yb-node-2
      - yb-node-3
      - ipfs

profiles:
  compute:
    # Smaller resources for testnet to save costs
    yb-node-1:
      resources:
        cpu:
          units: 1.0  # Reduced from 2.0
        memory:
          size: 2Gi   # Reduced from 4Gi
        storage:
          - name: data
            size: 20Gi  # Reduced from 50Gi

    yb-node-2:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          - name: data
            size: 20Gi

    yb-node-3:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          - name: data
            size: 20Gi

    api:
      resources:
        cpu:
          units: 0.5  # Reduced from 1.0
        memory:
          size: 512Mi # Reduced from 1Gi
        storage:
          - size: 512Mi

    ipfs:
      resources:
        cpu:
          units: 1.0  # Reduced from 2.0
        memory:
          size: 2Gi   # Reduced from 4Gi
        storage:
          - name: data
            size: 20Gi  # Reduced from 100Gi

  placement:
    dcloud:
      pricing:
        # Higher bids for testnet (2x increase from previous attempt)
        yb-node-1:
          denom: uakt
          amount: 2500
        yb-node-2:
          denom: uakt
          amount: 2500
        yb-node-3:
          denom: uakt
          amount: 2500
        api:
          denom: uakt
          amount: 1500
        ipfs:
          denom: uakt
          amount: 2500

deployment:
  yb-node-1:
    dcloud:
      profile: yb-node-1
      count: 1

  yb-node-2:
    dcloud:
      profile: yb-node-2
      count: 1

  yb-node-3:
    dcloud:
      profile: yb-node-3
      count: 1

  api:
    dcloud:
      profile: api
      count: 1

  ipfs:
    dcloud:
      profile: ipfs
      count: 1
