---
# Simplified Akash SDL for testing provider bids
# Just the API service, no databases, no persistent storage

version: "2.0"

services:
  # GraphQL API Service only
  api:
    image: ghcr.io/alternatefutures/service-cloud-api:testnet
    env:
      - NODE_ENV=production
      - PORT=4000
    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api-simple-test.alternatefutures.ai

profiles:
  compute:
    api:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi

  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000

deployment:
  api:
    dcloud:
      profile: api
      count: 1
