---
# Akash SDL (Stack Definition Language) for Alternate Futures Backend
# This deploys the GraphQL API + PostgreSQL to Akash Network

version: "2.0"

services:
  postgres:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=alternatefutures
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here_change_this
    expose:
      - port: 5432
        as: 5432
        to:
          - service: api
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data
          readOnly: false

  api:
    image: alternatefutures/backend:latest
    env:
      # Database
      - DATABASE_URL=postgresql://postgres:your_secure_password_here_change_this@postgres:5432/alternatefutures

      # App Config
      - NODE_ENV=production
      - PORT=4000

      # JWT Secret (CHANGE THIS!)
      - JWT_SECRET=your_jwt_secret_min_32_chars_please_change_this_in_production

      # Email (Resend)
      - RESEND_API_KEY=your_resend_api_key

      # Storage (IPFS/Arweave)
      - PINATA_JWT=your_pinata_jwt
      - PINATA_GATEWAY=your-gateway.mypinata.cloud
      - TURBO_WALLET_KEY=your_turbo_wallet_key

      # Optional: Analytics
      - SENTRY_DSN=your_sentry_dsn

    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api.alternatefutures.ai
    depends_on:
      - postgres

profiles:
  compute:
    api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 512Mi

    postgres:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          size: 10Gi

  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000
        postgres:
          denom: uakt
          amount: 1000

deployment:
  api:
    dcloud:
      profile: api
      count: 1

  postgres:
    dcloud:
      profile: postgres
      count: 1
