---
# Infisical Secrets Manager on Akash - FIXED VERSION
# Based on working deployment from INFISICAL_ON_AKASH_GUIDE.md
version: "2.0"

services:
  infisical:
    image: infisical/infisical:latest-postgres
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
        accept:
          - secrets.alternatefutures.ai
    env:
      # ENCRYPTION_KEY must be exactly 32 hex characters!
      - ENCRYPTION_KEY=f3c6c72e12a7e5d1b8f9a2c7d4e6f8a9
      - AUTH_SECRET=9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b
      - DB_CONNECTION_URI=postgres://postgres:infisical2024@postgres:5432/infisical
      - REDIS_URL=redis://redis:6379
      - SITE_URL=https://secrets.alternatefutures.ai
      - TELEMETRY_ENABLED=false
      - NODE_ENV=production
    command:
      - sh
      - -c
      - |
        cd /backend
        echo "Waiting 60s for PostgreSQL to be ready..."
        sleep 60
        echo "Starting Infisical..."
        npm run start

  postgres:
    image: postgres:15-alpine
    expose:
      - port: 5432
        to:
          - service: infisical
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=infisical2024
      - POSTGRES_DB=infisical
      - PGDATA=/data/pgdata
    params:
      storage:
        data:
          mount: /data
          readOnly: false

  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        to:
          - service: infisical

profiles:
  compute:
    infisical:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    postgres:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
          - name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta3
    redis:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 256Mi
        storage:
          size: 512Mi

  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      attributes:
        host: akash
      pricing:
        infisical:
          denom: uakt
          amount: 10000
        postgres:
          denom: uakt
          amount: 5000
        redis:
          denom: uakt
          amount: 2500

deployment:
  infisical:
    akash:
      profile: infisical
      count: 1
  postgres:
    akash:
      profile: postgres
      count: 1
  redis:
    akash:
      profile: redis
      count: 1
