---
# Akash SDL - YugabyteDB cluster (standalone)
version: "2.0"

services:
  # YugabyteDB Node 1 - Master + TServer
  yb-node-1:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=your_secure_password_here_change_this
      - YSQL_DB=alternatefutures
    expose:
      # YSQL - public TCP for app connections
      - port: 5433
        as: 5433
        proto: tcp
        to:
          - global: true
      # Master RPC - for cluster coordination
      - port: 7100
        as: 7100
        to:
          - service: yb-node-2
          - service: yb-node-3
      # TServer RPC - for data replication
      - port: 9100
        as: 9100
        to:
          - service: yb-node-2
          - service: yb-node-3
      # Admin UI
      - port: 15000
        as: 15000
        to:
          - global: true
        accept:
          - yb.alternatefutures.ai
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # YugabyteDB Node 2 - Master + TServer
  yb-node-2:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-2"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=your_secure_password_here_change_this
      - YSQL_DB=alternatefutures
    expose:
      # Master RPC
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-3
      # TServer RPC
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-3
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

  # YugabyteDB Node 3 - Master + TServer
  yb-node-3:
    image: yugabytedb/yugabyte:2.20.1.0-b2
    command:
      - "/home/yugabyte/bin/yugabyted"
      - "start"
      - "--advertise_address=yb-node-3"
      - "--join=yb-node-1"
      - "--master_flags=replication_factor=3"
      - "--tserver_flags=ysql_enable_auth=true"
      - "--daemon=false"
    env:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=your_secure_password_here_change_this
      - YSQL_DB=alternatefutures
    expose:
      # Master RPC
      - port: 7100
        as: 7100
        to:
          - service: yb-node-1
          - service: yb-node-2
      # TServer RPC
      - port: 9100
        as: 9100
        to:
          - service: yb-node-1
          - service: yb-node-2
    params:
      storage:
        data:
          mount: /mnt/disk0
          readOnly: false

profiles:
  compute:
    yb-node-1:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 4Gi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
    yb-node-2:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 4Gi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
    yb-node-3:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 4Gi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3

  placement:
    dcloud:
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        yb-node-1:
          denom: uakt
          amount: 100
        yb-node-2:
          denom: uakt
          amount: 100
        yb-node-3:
          denom: uakt
          amount: 100

deployment:
  yb-node-1:
    dcloud:
      profile: yb-node-1
      count: 1
  yb-node-2:
    dcloud:
      profile: yb-node-2
      count: 1
  yb-node-3:
    dcloud:
      profile: yb-node-3
      count: 1
