---
# Akash SDL - IPFS + Jaeger (data services)
# OTel Collector removed — Jaeger exposes OTLP ports (4317/4318) natively.
# The API's redeploy script falls back to Jaeger's OTLP endpoint automatically.
version: "2.0"

services:
  # IPFS Node (Kubo)
  ipfs:
    image: ipfs/kubo:latest
    env:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    expose:
      # API port (public - used by api service)
      - port: 5001
        as: 5001
        to:
          - global: true
      # Gateway port
      - port: 8080
        as: 8080
        to:
          - global: true
        accept:
          - ipfs.alternatefutures.ai
      # Swarm port
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true
    params:
      storage:
        data:
          mount: /data/ipfs
          readOnly: false

  # Jaeger - Tracing storage, UI, and OTLP receiver
  jaeger:
    image: jaegertracing/all-in-one:latest
    env:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    expose:
      # Jaeger UI
      - port: 16686
        as: 80
        to:
          - global: true
        accept:
          - jaeger.alternatefutures.ai
      # OTLP gRPC receiver (primary telemetry endpoint)
      - port: 4317
        as: 4317
        to:
          - global: true
      # OTLP HTTP receiver
      - port: 4318
        as: 4318
        to:
          - global: true
    params:
      storage:
        data:
          mount: /badger
          readOnly: false

profiles:
  compute:
    ipfs:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - size: 1Gi
          - name: data
            size: 100Gi
            attributes:
              persistent: true
              class: beta3
    jaeger:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1.5Gi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3

  placement:
    dcloud:
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        ipfs:
          denom: uakt
          amount: 100
        jaeger:
          denom: uakt
          amount: 50

deployment:
  ipfs:
    dcloud:
      profile: ipfs
      count: 1
  jaeger:
    dcloud:
      profile: jaeger
      count: 1
