---
version: "2.0"

services:
  auth-api:
    image: node:20-alpine
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - auth.alternatefutures.ai
    env:
      # Core Configuration
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=/app/data/auth.db

      # JWT Secrets
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d

      # URLs (will use Akash ingress URL)
      - CORS_ORIGIN=*
    command:
      - sh
      - -c
      - |
        echo "Installing git and build tools..."
        apk add --no-cache git python3 make g++

        echo "Cloning service-auth repository..."
        git clone https://github.com/alternatefutures/service-auth.git /app
        cd /app

        echo "Creating data directory..."
        mkdir -p /app/data

        echo "Installing ALL dependencies..."
        NODE_ENV=development npm install

        echo "Starting service-auth with tsx (TypeScript runner)..."
        NODE_ENV=production ./node_modules/.bin/tsx src/index.ts

profiles:
  compute:
    auth-api:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 2Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        auth-api:
          denom: uakt
          amount: 1000

deployment:
  auth-api:
    akash:
      profile: auth-api
      count: 1
