---
version: "2.0"

services:
  api:
    image: node:20-slim
    expose:
      - port: 4000
        as: 80
        to:
          - global: true
        accept:
          - api.alternatefutures.ai
    env:
      # Database (internal service)
      - DATABASE_URL=${DATABASE_URL}

      # Server
      - PORT=4000
      - NODE_ENV=production

      # JWT (must match service-auth)
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=7d

      # Auth Service (deployed on Akash)
      - AUTH_SERVICE_URL=https://irqnjdusb9c813k10bl2gd92l0.ingress.europlots.com

      # CORS
      - APP_URL=*

      # Prisma engine type
      - PRISMA_CLIENT_ENGINE_TYPE=binary

    command:
      - sh
      - -c
      - |
        echo "Installing system dependencies..."
        apt-get update && apt-get install -y --no-install-recommends git openssl ca-certificates python3 make g++

        echo "Cloning service-cloud-api repository..."
        git clone https://github.com/alternatefutures/service-cloud-api.git /app
        cd /app

        echo "Installing ALL dependencies (including devDependencies)..."
        NODE_ENV=development npm install

        echo "Generating Prisma client..."
        npx prisma generate

        echo "Waiting 30s for PostgreSQL to be ready..."
        sleep 30

        echo "Pushing database schema..."
        npx prisma db push --accept-data-loss

        echo "Starting service-cloud-api with tsx..."
        ./node_modules/.bin/tsx src/index.ts

  postgres:
    image: postgres:15-alpine
    expose:
      - port: 5432
        to:
          - service: api
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=alternatefutures

profiles:
  compute:
    api:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          - size: 4Gi
    postgres:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 2Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        api:
          denom: uakt
          amount: 1000
        postgres:
          denom: uakt
          amount: 1000

deployment:
  api:
    akash:
      profile: api
      count: 1
  postgres:
    akash:
      profile: postgres
      count: 1
