---
# Caddy Gateway with IP Lease for Let's Encrypt
# Requires provider with IP leasing enabled
version: "2.0"

services:
  gateway:
    image: caddy:2-alpine
    expose:
      - port: 80
        as: 80
        ip: "leased"
        to:
          - global: true
      - port: 443
        as: 443
        ip: "leased"
        to:
          - global: true
    env:
      - API_BACKEND=https://cjrdmusuql9e34bevi8mjgj8pg.ingress.europlots.com
      - AUTH_BACKEND=https://uilm2birnle5b7ffcqvsgpolc4.ingress.europlots.com
      - ACME_EMAIL=admin@alternatefutures.ai
    command:
      - sh
      - -c
      - |
        cat > /etc/caddy/Caddyfile << 'CADDYFILE'
        {
            email {$ACME_EMAIL}
        }

        api.alternatefutures.ai {
            reverse_proxy {$API_BACKEND} {
                header_up Host api.alternatefutures.ai
                header_up X-Forwarded-Proto https
                transport http {
                    tls
                    tls_insecure_skip_verify
                }
            }
        }

        auth.alternatefutures.ai {
            reverse_proxy {$AUTH_BACKEND} {
                header_up Host auth.alternatefutures.ai
                header_up X-Forwarded-Proto https
                transport http {
                    tls
                    tls_insecure_skip_verify
                }
            }
        }
        CADDYFILE

        caddy run --config /etc/caddy/Caddyfile

profiles:
  compute:
    gateway:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          - size: 1Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        gateway:
          denom: uakt
          amount: 1000

deployment:
  gateway:
    akash:
      profile: gateway
      count: 1
