---
# Caddy Edge Proxy with Dynamic Domain Management
# Uses Caddy's Admin API for instant domain updates
# IP Lease: 77.76.13.213 (DSEQ: 24559747)
version: '2.0'

services:
  caddy:
    image: caddy:2-alpine
    env:
      # Backend URLs (Akash ingress endpoints) - Updated Dec 10, 2024
      - BACKEND_API=e1i0489b8hfct0qqlcsn5it8io.ingress.gpu.subangle.com
      - BACKEND_AUTH=2napn78u2le0h18a3q3kfqk4kg.ingress.gpu.subangle.com
      - BACKEND_SECRETS=9tnnbebe65bvt1vd2g6k67a72g.ingress.parallelnode.de
      # Admin API key (change this!)
      - CADDY_ADMIN_KEY=${CADDY_ADMIN_KEY}
      # TLS certificate bundle (fullchain + private key), base64-encoded.
      # IMPORTANT: Do not commit this; inject via secrets manager/CI.
      - SSL_CERT_B64=${SSL_CERT_B64}
    command:
      - /bin/sh
      - -c
      - |
        set -e
        echo "=== AlternateFutures Edge Node (Caddy) ==="

        # Install SSL certificate
        mkdir -p /etc/caddy/certs
        echo "${SSL_CERT_B64}" | base64 -d > /etc/caddy/certs/alternatefutures.pem
        chmod 600 /etc/caddy/certs/alternatefutures.pem

        # Extract cert chain and key for Caddy
        # The PEM file contains: certificate, intermediate cert, private key
        # Use sed to extract certificates (everything except the private key)
        sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' /etc/caddy/certs/alternatefutures.pem > /etc/caddy/certs/cert.pem
        # Use sed to extract private key
        sed -n '/-----BEGIN EC PRIVATE KEY-----/,/-----END EC PRIVATE KEY-----/p' /etc/caddy/certs/alternatefutures.pem > /etc/caddy/certs/key.pem
        chmod 600 /etc/caddy/certs/*.pem

        echo "Certificate file size: $(wc -c < /etc/caddy/certs/cert.pem) bytes"
        echo "Key file size: $(wc -c < /etc/caddy/certs/key.pem) bytes"

        # Create Caddyfile
        cat > /etc/caddy/Caddyfile << 'EOF'
        {
            # Admin API - listen on all interfaces for external access
            # SECURITY: bind admin locally; do not expose publicly
            admin 127.0.0.1:2019

            # Disable automatic HTTPS (we use our own cert)
            auto_https off

            # Logging
            log {
                output stdout
                format console
            }
        }

        # API Service
        api.alternatefutures.ai {
            tls /etc/caddy/certs/cert.pem /etc/caddy/certs/key.pem

            reverse_proxy https://{$BACKEND_API} {
                header_up Host {$BACKEND_API}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-For {remote_host}
                header_up X-Forwarded-Proto https
                transport http {
                    tls
                    tls_insecure_skip_verify
                }
            }

            header {
                Strict-Transport-Security "max-age=31536000; includeSubDomains"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "DENY"
            }
        }

        # Auth Service
        auth.alternatefutures.ai {
            tls /etc/caddy/certs/cert.pem /etc/caddy/certs/key.pem

            reverse_proxy https://{$BACKEND_AUTH} {
                header_up Host {$BACKEND_AUTH}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-For {remote_host}
                header_up X-Forwarded-Proto https
                transport http {
                    tls
                    tls_insecure_skip_verify
                }
            }

            header {
                Strict-Transport-Security "max-age=31536000; includeSubDomains"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "DENY"
            }
        }

        # Secrets Service (Infisical)
        secrets.alternatefutures.ai {
            tls /etc/caddy/certs/cert.pem /etc/caddy/certs/key.pem

            reverse_proxy https://{$BACKEND_SECRETS} {
                header_up Host {$BACKEND_SECRETS}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-For {remote_host}
                header_up X-Forwarded-Proto https
                transport http {
                    tls
                    tls_insecure_skip_verify
                }
            }

            header {
                Strict-Transport-Security "max-age=31536000; includeSubDomains"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "DENY"
            }
        }

        # Health check endpoint (internal)
        :8080 {
            respond /health 200 {
                body "OK"
            }
            respond /ready 200 {
                body "Ready"
            }
        }
        EOF

        echo "=== Starting Caddy ==="
        echo "Admin API bound to 127.0.0.1:2019"
        echo "HTTPS on port 443"
        exec caddy run --config /etc/caddy/Caddyfile
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: 'caddy'
      - port: 443
        as: 443
        to:
          - global: true
            ip: 'caddy'
      - port: 8080
        as: 8080
        to:
          - global: true # Health checks

profiles:
  compute:
    caddy:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    dcloud:
      pricing:
        caddy:
          denom: uakt
          amount: 10000

deployment:
  caddy:
    dcloud:
      profile: caddy
      count: 1

endpoints:
  caddy:
    kind: ip
