---
version: "2.0"

services:
  haproxy:
    image: alpine:3.19
    env:
      # Backend URLs (Akash ingress endpoints)
      - BACKEND_API=cjrdmusuql9e34bevi8mjgj8pg.ingress.europlots.com:443
      - BACKEND_AUTH=2svb4vnmb1fkdbudldgr7p3thg.ingress.europlots.com:443
      - BACKEND_SECRETS=9tnnbebe65bvt1vd2g6k67a72g.ingress.parallelnode.de:443
      # Let's Encrypt certificate (base64 encoded) - valid Dec 3, 2025 to Mar 3, 2026
      # Contains fullchain.cer + private key for api, auth, and secrets.alternatefutures.ai
      - SSL_CERT_B64=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyRENDQTE2Z0F3SUJBZ0lTQlYyc3BybEc3SnBuWGQweGU4WEVaQmhOTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpPREFlRncweU5URXlNRE13TkRBMU1EUmFGdzB5TmpBek1ETXdOREExTUROYU1DSXhJREFlQmdOVkJBTVRGMkZ3CmFTNWhiSFJsY201aGRHVm1kWFIxY21WekxtRnBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKK1dpVWJLeHRkc0hUK1lvZmZFNVl0d3ZJWVJBNTlMQnoyTXdlc3QxOVd4a1FuZldkV3plRzRRYldtM3BWMGs4dgpHei9KU2lHd2dQbUdiTXZub2Z1S0c2T0NBbUl3Z2dKZU1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBZEJnTlZIU1VFCkZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVUKd2pxeThvSncxeThZRmlrc0ZXRjBnWTcxQWhRd0h3WURWUjBqQkJnd0ZvQVVqdzBUb3ZZdWZ0RlFiRE1ZT0YxWgpqaU55a2Nvd01nWUlLd1lCQlFVSEFRRUVKakFrTUNJR0NDc0dBUVVGQnpBQ2hoWm9kSFJ3T2k4dlpUZ3VhUzVzClpXNWpjaTV2Y21jdk1Ga0dBMVVkRVFSU01GQ0NGMkZ3YVM1aGJIUmxjbTVoZEdWbWRYUjFjbVZ6TG1GcGdoaGgKZFhSb0xtRnNkR1Z5Ym1GMFpXWjFkSFZ5WlhNdVlXbUNHM05sWTNKbGRITXVZV3gwWlhKdVlYUmxablYwZFhKbApjeTVoYVRBVEJnTlZIU0FFRERBS01BZ0dCbWVCREFFQ0FUQXRCZ05WSFI4RUpqQWtNQ0tnSUtBZWhoeG9kSFJ3Ck9pOHZaVGd1WXk1c1pXNWpjaTV2Y21jdk56Z3VZM0pzTUlJQkNnWUtLd1lCQkFIV2VRSUVBZ1NCK3dTQitBRDIKQUhVQVpCSEViS1FTN0tlSkhLSUNMZ0M4cTA4b0I5UWVOU2VyNnY3VkE4bDl6ZkFBQUFHYTRwZ3NLQUFBQkFNQQpSakJFQWlBTG03WGZFeENuc0twaDQ1eGZTZXpucys1L3ZTZmxMclEvQjd6NTNyR2JIQUlnWDFhMFRpMGxGNG9nCkJHdkw0eVNMd2w1RlFXZDVUK1Jod1JSb2pSYXpUSkFBZlFEakk0M3lqYUtJNEtyZ3JQRDZrTW1GOExhLzlkS2wKSjdBQi9CeEVXTVMyNkFBQUFacmltRFkwQUFnQUFBVUFKekVRdVFRREFFWXdSQUlnSExRMHlTQnQrYzg0ZFJGUgpOcTVJSExGQ2habFhnVk96eVNIOFBHMTRVdHNDSUY2NmlTM2dFbWt4UjVCMXdzY3pobFFHSVBYaDNwNUg0R01EClNHc3JVSU0xTUFvR0NDcUdTTTQ5QkFNREEyZ0FNR1VDTVFERUtDcVZITFRzcWltLzhjSHdnM01JVVNMellicXIKUlRmR1ZkdmhNSGJMMXZ1SUdPQmZiaFVaM3B0RjVVQkRJL2dDTUhidzVkcUZrNGw0K1U0UnRMaCtFQ0xzNXBYSQpRK3RQOVdJelE4a0ljQVNjeHFXZGRPKzdPcVVGd2JFWmhjeWxvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFVmpDQ0FqNmdBd0lCQWdJUVk1V1RZOEpPY0lKeFdSaS93OWZ0VmpBTkJna3Foa2lHOXcwQkFRc0ZBREJQCk1Rc3dDUVlEVlFRR0V3SlZVekVwTUNjR0ExVUVDaE1nU1c1MFpYSnVaWFFnVTJWamRYSnBkSGtnVW1WelpXRnkKWTJnZ1IzSnZkWEF4RlRBVEJnTlZCQU1UREVsVFVrY2dVbTl2ZENCWU1UQWVGdzB5TkRBek1UTXdNREF3TURCYQpGdzB5TnpBek1USXlNelU1TlRsYU1ESXhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWURWUVFLRXcxTVpYUW5jeUJGCmJtTnllWEIwTVFzd0NRWURWUVFERXdKRk9EQjJNQkFHQnlxR1NNNDlBZ0VHQlN1QkJBQWlBMklBQk5GbDhsN2MKUzdRTUFwelNzdnJ1Nld5ck9xNDRvZlRVT1RJenhVTFV6RE1NTk1jaElKQndYT2hpTHh4eHMwTFhlYjVHRGNIYgpSNkVUb01mZmdTWmpPOVNOSGZZOWdqTXk5dlFyNS9XV09yUVRaeGg3YXo2TlNObnEzdTJ1YlQ2SFRLT0IrRENCCjlUQU9CZ05WSFE4QkFmOEVCQU1DQVlZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUIKTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFBd0hRWURWUjBPQkJZRUZJOE5FNkwyTG43UlVHd3pHRGhkV1k0agpjcEhLTUI4R0ExVWRJd1FZTUJhQUZIbTBXZVo3dHVYa0FYT0FDSWpJR2xqMjZadHVNRElHQ0NzR0FRVUZCd0VCCkJDWXdKREFpQmdnckJnRUZCUWN3QW9ZV2FIUjBjRG92TDNneExta3ViR1Z1WTNJdWIzSm5MekFUQmdOVkhTQUUKRERBS01BZ0dCbWVCREFFQ0FUQW5CZ05WSFI4RUlEQWVNQnlnR3FBWWhoWm9kSFJ3T2k4dmVERXVZeTVzWlc1agpjaTV2Y21jdk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQm5FMGhHSU5Lc0NZV2kwWHgxeWd4RDVxaWhFalowClJJM3RUWnoxd3VBVEgzWndZUElwOTdrV0VheWFuRDFqMGNEaElZenk0Q2tEbzJqQjhENXQwYTZ6Wld6bHI5OGQKQVFGTmg4dUtKa0lIZExTaHkrblV5ZVp4YzViTmVNcDFMdTBnU3pFNE1jcWZtTk12SXBlaXdXU1lPOXc4Mk9iOApvdHZYY08ySlVZaTNzdkhJV1JtMys3MDdEVWJMNTFYTWNZMmlaZGxDcTRXYTluYnVrM1dUVTRncjZMWThNelZBCmFEUUcyKzRVM2VKNnFVRjEwYkJuUjF1dVZ5RFlzOVJocnd1Y1JWbmZ1RGoyOUNNTFRzcGxNNWY1d1NWNWhVcG0KVXdwL3ZWN000dzRhR3VudDc0a29YNzFuNEVkYWdDc0wvWWs1K21BUVUwK3R1ZTBLT2ZBVi9SNnQxaytYazlzMgpITVFGZW94cHBmekFWQzA0RmRHOU0rQUMySld4bUZTdDZCQ3VoM0NFZXkzZkU1MlFyajlZTTc1cnR2SWpzbS8xCkhsK3UvL1dxeG51MVpRNGpwYStWcHVaaUdPbFdycVNQOWVvZ2RPaENHaXNueWV3V0p3UlFPcUsxNndpR3laZVIKeHMvQmVrdzY1dndTSWFWa0JydVBpVGZNT28wWmg0Z1ZhOC9xSmdNYkpieXJ3d0c5N3ovUFJnbUxLQ0RsOHozZAp0QTBaN3FxN2Z0YTBHbDI0dXl1QjA1ZHFJNUoxTHZBekt1V2RJalQxdFA4cUNveFNFL3hwaXg4aFgyZHQzaCsvCmp1alVnRlBGWjBFVloweFN5Qk5SRjNNYm9HWm5ZWEZVeHBOalRXUEtwYWdESEpRbXFyQWNEbVdKbk1zRlkzalMKdTFpZ3YzT2VmbldqU1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gRUMgUFJJVkFURSBLRVktLS0tLQpNSGNDQVFFRUlJM05GTTlmM2hUMXE3NDlmK0pIL0FIYUZoSFZYSUtQS0pDdVREYlVPMW5Fb0FvR0NDcUdTTTQ5CkF3RUhvVVFEUWdBRStXaVViS3h0ZHNIVCtZb2ZmRTVZdHd2SVlSQTU5TEJ6Mk13ZXN0MTlXeGtRbmZXZFd6ZUcKNFFiV20zcFYwazh2R3ovSlNpR3dnUG1HYk12bm9mdUtHdz09Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
    command:
      - /bin/sh
      - -c
      - |
        set -e

        echo "=== AlternateFutures Edge Node (Akash IP Lease) ==="
        echo "SSL: Let's Encrypt certificate (valid Dec 3, 2025 - Mar 3, 2026)"

        # Install dependencies including HAProxy
        apk add --no-cache haproxy openssl

        # Create directory structure
        mkdir -p /etc/haproxy/certs
        mkdir -p /etc/haproxy/maps
        mkdir -p /etc/haproxy/errors

        # Create domain map
        cat > /etc/haproxy/maps/domains.map << 'DOMAINMAP'
        api.alternatefutures.ai     be_api
        auth.alternatefutures.ai    be_auth
        secrets.alternatefutures.ai be_secrets
        DOMAINMAP

        # Create error pages
        for code in 400 403 408 500 502 503 504; do
          cat > /etc/haproxy/errors/${code}.http << EOF
        HTTP/1.1 ${code}
        Content-Type: application/json
        Connection: close

        {"error": "HTTP ${code}", "message": "Edge node error", "provider": "AlternateFutures"}
        EOF
        done

        # Install Let's Encrypt certificate from embedded base64
        echo "=== Installing Let's Encrypt SSL certificate ==="
        echo "${SSL_CERT_B64}" | base64 -d > /etc/haproxy/certs/api.alternatefutures.ai.pem
        chmod 600 /etc/haproxy/certs/api.alternatefutures.ai.pem
        # Same cert covers all three domains (SAN certificate)
        cp /etc/haproxy/certs/api.alternatefutures.ai.pem /etc/haproxy/certs/auth.alternatefutures.ai.pem
        cp /etc/haproxy/certs/api.alternatefutures.ai.pem /etc/haproxy/certs/secrets.alternatefutures.ai.pem
        echo "Installed Let's Encrypt certificate for api, auth, and secrets.alternatefutures.ai"

        # Verify certificate
        echo "=== Certificate info ==="
        openssl x509 -in /etc/haproxy/certs/api.alternatefutures.ai.pem -noout -subject -dates -issuer

        # Create HAProxy configuration
        cat > /etc/haproxy/haproxy.cfg << 'HAPROXYCONFIG'
        global
            log stdout format raw local0
            maxconn 4096
            tune.ssl.default-dh-param 2048
            ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
            ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

        defaults
            log     global
            mode    http
            option  httplog
            option  dontlognull
            option  forwardfor
            timeout connect 10s
            timeout client  30s
            timeout server  30s
            timeout http-request 10s
            timeout http-keep-alive 10s

        frontend fe_stats
            bind *:8404
            mode http
            stats enable
            stats uri /stats
            stats refresh 10s
            http-request use-service prometheus-exporter if { path /metrics }

        frontend fe_http
            bind *:80
            mode http
            # Redirect all HTTP to HTTPS
            http-request redirect scheme https code 301 unless { ssl_fc }

        frontend fe_https
            bind *:443 ssl crt /etc/haproxy/certs/ alpn h2,http/1.1
            mode http

            # Security headers
            http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
            http-response set-header X-Content-Type-Options nosniff
            http-response set-header X-Frame-Options DENY

            # Rate limiting (100 requests per 10 seconds per IP)
            stick-table type ip size 100k expire 30s store http_req_rate(10s)
            http-request track-sc0 src
            http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }

            # Route based on domain
            use_backend %[req.hdr(host),lower,map(/etc/haproxy/maps/domains.map,be_default)]

        backend be_api
            mode http
            option httpchk GET /health
            http-check expect status 200
            server akash_api ${BACKEND_API} ssl verify none check inter 10s fall 3 rise 2

        backend be_auth
            mode http
            option httpchk GET /health
            http-check expect status 200
            server akash_auth ${BACKEND_AUTH} ssl verify none check inter 10s fall 3 rise 2

        backend be_secrets
            mode http
            option httpchk GET /api/status
            http-check expect status 200
            server akash_secrets ${BACKEND_SECRETS} ssl verify none sni str(9tnnbebe65bvt1vd2g6k67a72g.ingress.parallelnode.de) check inter 10s fall 3 rise 2

        backend be_default
            mode http
            http-request deny deny_status 404
        HAPROXYCONFIG

        # Replace environment variables in config
        sed -i "s|\${BACKEND_API}|${BACKEND_API}|g" /etc/haproxy/haproxy.cfg
        sed -i "s|\${BACKEND_AUTH}|${BACKEND_AUTH}|g" /etc/haproxy/haproxy.cfg
        sed -i "s|\${BACKEND_SECRETS}|${BACKEND_SECRETS}|g" /etc/haproxy/haproxy.cfg

        # Validate configuration
        echo "=== Validating HAProxy configuration ==="
        haproxy -c -f /etc/haproxy/haproxy.cfg

        # Start HAProxy
        echo "=== Starting HAProxy ==="
        echo "Edge node ready on ports 80, 443, 8404"
        exec haproxy -f /etc/haproxy/haproxy.cfg -db
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: "haproxy"
      - port: 443
        as: 443
        to:
          - global: true
            ip: "haproxy"
      - port: 8404
        as: 8404
        to:
          - global: true

profiles:
  compute:
    haproxy:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    dcloud:
      pricing:
        haproxy:
          denom: uakt
          amount: 10000

deployment:
  haproxy:
    dcloud:
      profile: haproxy
      count: 1

endpoints:
  haproxy:
    kind: ip
