---
version: "2.0"

services:
  haproxy:
    image: alpine:3.19
    env:
      # Backend URLs (Akash ingress endpoints)
      - BACKEND_API=cjrdmusuql9e34bevi8mjgj8pg.ingress.europlots.com:443
      - BACKEND_AUTH=2svb4vnmb1fkdbudldgr7p3thg.ingress.europlots.com:443
      - BACKEND_SECRETS=9tnnbebe65bvt1vd2g6k67a72g.ingress.parallelnode.de:443
      # TLS certificate bundle (fullchain + private key), base64-encoded.
      # IMPORTANT: Do not commit this; inject via secrets manager/CI.
      - SSL_CERT_B64=${SSL_CERT_B64}
    command:
      - /bin/sh
      - -c
      - |
        set -e

        echo "=== AlternateFutures Edge Node (Akash IP Lease) ==="
        echo "SSL: Let's Encrypt certificate (valid Dec 3, 2025 - Mar 3, 2026)"

        # Install dependencies including HAProxy
        apk add --no-cache haproxy openssl

        # Create directory structure
        mkdir -p /etc/haproxy/certs
        mkdir -p /etc/haproxy/maps
        mkdir -p /etc/haproxy/errors

        # Create domain map
        cat > /etc/haproxy/maps/domains.map << 'DOMAINMAP'
        api.alternatefutures.ai     be_api
        auth.alternatefutures.ai    be_auth
        secrets.alternatefutures.ai be_secrets
        DOMAINMAP

        # Create error pages
        for code in 400 403 408 500 502 503 504; do
          cat > /etc/haproxy/errors/${code}.http << EOF
        HTTP/1.1 ${code}
        Content-Type: application/json
        Connection: close

        {"error": "HTTP ${code}", "message": "Edge node error", "provider": "AlternateFutures"}
        EOF
        done

        # Install Let's Encrypt certificate from embedded base64
        echo "=== Installing Let's Encrypt SSL certificate ==="
        echo "${SSL_CERT_B64}" | base64 -d > /etc/haproxy/certs/api.alternatefutures.ai.pem
        chmod 600 /etc/haproxy/certs/api.alternatefutures.ai.pem
        # Same cert covers all three domains (SAN certificate)
        cp /etc/haproxy/certs/api.alternatefutures.ai.pem /etc/haproxy/certs/auth.alternatefutures.ai.pem
        cp /etc/haproxy/certs/api.alternatefutures.ai.pem /etc/haproxy/certs/secrets.alternatefutures.ai.pem
        echo "Installed Let's Encrypt certificate for api, auth, and secrets.alternatefutures.ai"

        # Verify certificate
        echo "=== Certificate info ==="
        openssl x509 -in /etc/haproxy/certs/api.alternatefutures.ai.pem -noout -subject -dates -issuer

        # Create HAProxy configuration
        cat > /etc/haproxy/haproxy.cfg << 'HAPROXYCONFIG'
        global
            log stdout format raw local0
            maxconn 4096
            tune.ssl.default-dh-param 2048
            ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
            ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

        defaults
            log     global
            mode    http
            option  httplog
            option  dontlognull
            option  forwardfor
            timeout connect 10s
            timeout client  30s
            timeout server  30s
            timeout http-request 10s
            timeout http-keep-alive 10s

        frontend fe_stats
            bind *:8404
            mode http
            stats enable
            stats uri /stats
            stats refresh 10s
            http-request use-service prometheus-exporter if { path /metrics }

        frontend fe_http
            bind *:80
            mode http
            # Redirect all HTTP to HTTPS
            http-request redirect scheme https code 301 unless { ssl_fc }

        frontend fe_https
            bind *:443 ssl crt /etc/haproxy/certs/ alpn h2,http/1.1
            mode http

            # Security headers
            http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
            http-response set-header X-Content-Type-Options nosniff
            http-response set-header X-Frame-Options DENY

            # Rate limiting (100 requests per 10 seconds per IP)
            stick-table type ip size 100k expire 30s store http_req_rate(10s)
            http-request track-sc0 src
            http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }

            # Route based on domain
            use_backend %[req.hdr(host),lower,map(/etc/haproxy/maps/domains.map,be_default)]

        backend be_api
            mode http
            option httpchk GET /health
            http-check expect status 200
            server akash_api ${BACKEND_API} ssl verify none check inter 10s fall 3 rise 2

        backend be_auth
            mode http
            option httpchk GET /health
            http-check expect status 200
            server akash_auth ${BACKEND_AUTH} ssl verify none check inter 10s fall 3 rise 2

        backend be_secrets
            mode http
            option httpchk GET /api/status
            http-check expect status 200
            server akash_secrets ${BACKEND_SECRETS} ssl verify none sni str(9tnnbebe65bvt1vd2g6k67a72g.ingress.parallelnode.de) check inter 10s fall 3 rise 2

        backend be_default
            mode http
            http-request deny deny_status 404
        HAPROXYCONFIG

        # Replace environment variables in config
        sed -i "s|\${BACKEND_API}|${BACKEND_API}|g" /etc/haproxy/haproxy.cfg
        sed -i "s|\${BACKEND_AUTH}|${BACKEND_AUTH}|g" /etc/haproxy/haproxy.cfg
        sed -i "s|\${BACKEND_SECRETS}|${BACKEND_SECRETS}|g" /etc/haproxy/haproxy.cfg

        # Validate configuration
        echo "=== Validating HAProxy configuration ==="
        haproxy -c -f /etc/haproxy/haproxy.cfg

        # Start HAProxy
        echo "=== Starting HAProxy ==="
        echo "Edge node ready on ports 80, 443, 8404"
        exec haproxy -f /etc/haproxy/haproxy.cfg -db
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: "haproxy"
      - port: 443
        as: 443
        to:
          - global: true
            ip: "haproxy"
      - port: 8404
        as: 8404
        to:
          - global: true

profiles:
  compute:
    haproxy:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    dcloud:
      pricing:
        haproxy:
          denom: uakt
          amount: 10000

deployment:
  haproxy:
    dcloud:
      profile: haproxy
      count: 1

endpoints:
  haproxy:
    kind: ip
